# Generated by Django 5.1.2 on 2024-10-22 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0003_user_alter_dailyintake_user_alter_mealoftheday_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyintake',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_intakes', to='base.user'),
        ),
        migrations.AlterField(
            model_name='dailyintake',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealoftheday',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_of_day', to='base.mealnutrition'),
        ),
        migrations.AlterField(
            model_name='mealoftheday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='base.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='dailyintake',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_intake'),
        ),
    ]
