# Generated by Django 5.1.2 on 2024-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0004_alter_dailyintake_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealnutrition',
            name='calories',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='carbohydrates_total_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='cholesterol_mg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='fat_saturated_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='fat_total_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='fiber_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='potassium_mg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='protein_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='serving_size_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='sodium_mg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealnutrition',
            name='sugar_g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
